wandb_version: 1

wandb_log:
  desc: null
  value: false
run_name:
  desc: null
  value: Flash Attention - mps
project_name:
  desc: null
  value: 'Attention Benchmark '
out_dir:
  desc: null
  value: out
eval_interval:
  desc: null
  value: 2000
log_interval:
  desc: null
  value: 1
eval_iters:
  desc: null
  value: 200
eval_only:
  desc: null
  value: false
always_save_checkpoint:
  desc: null
  value: true
init_from:
  desc: null
  value: scratch
gradient_accumulation_steps:
  desc: null
  value: 40
batch_size:
  desc: null
  value: 2
block_size:
  desc: null
  value: 512
n_layer:
  desc: null
  value: 6
n_head:
  desc: null
  value: 8
n_embd:
  desc: null
  value: 512
dropout:
  desc: null
  value: 0.0
bias:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0006
max_iters:
  desc: null
  value: 1000
weight_decay:
  desc: null
  value: 0.1
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
grad_clip:
  desc: null
  value: 1.0
decay_lr:
  desc: null
  value: true
warmup_iters:
  desc: null
  value: 200
lr_decay_iters:
  desc: null
  value: 1000
min_lr:
  desc: null
  value: 6.0e-05
backend:
  desc: null
  value: gloo
device:
  desc: null
  value: mps
dtype:
  desc: null
  value: float32
compile:
  desc: null
  value: false
ddp:
  desc: null
  value: false
master_process:
  desc: null
  value: true
seed_offset:
  desc: null
  value: 0
ddp_world_size:
  desc: null
  value: 1
tokens_per_iter:
  desc: null
  value: 40960
device_type:
  desc: null
  value: mps
iter_num:
  desc: null
  value: 0
best_val_loss:
  desc: null
  value: 1000000000.0
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720424868
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.17.4
      6: 4.40.2
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
