wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720331834
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 23
      4: 3.8.13
      5: 0.17.4
      6: 4.40.2
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
